name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Validate SAM Template
      run: |
        sam validate --template-file source/template.yml --region ${{ secrets.AWS_REGION }}

    - name: Package SAM Application
      run: |
        sam package --template-file source/template.yml --output-template-file source/packaged.yaml --s3-bucket ${{ secrets.S3_BUCKET }} --region ${{ secrets.AWS_REGION }}

    - name: Deploy SAM Application
      run: |
        sam deploy --template-file source/packaged.yaml --stack-name sam-raju-master-cfs --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
